### ISSUE TITLE
particel not working :(

### ISSUE THREAD

**Issue by DampfWaffel** [MorkaZ/MorkazSk#20]
Particel wont Spawn and Skript throw a error in the console.

Server Version: Paper-335 1.15.2
Skript Version: 2.5-alpha3
MorkazSk Version: 1.2
ProtocolLib Version: 4.5.1

```[21:48:26] [Server thread/INFO]: [Skript] DampfWaffel issued effect command: spawn 20 of particle "FLAME" for player at player offset by 0.2, 0.2, 0.2 with speed 0.05
[21:48:26] [Server thread/WARN]: [ProtocolLib] Loaded class com.morkaz.morkazsk.optionals.protocollib.EffShowParticleToPlayer from MorkazSk v1.2 which is not a depend, softdepend or loadbefore of this plugin.
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[21:48:26] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:48:26] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:48:26] [Server thread/ERROR]: #!#! Here is full list of them:
[21:48:26] [Server thread/ERROR]: #!#! SkBee v1.3.1 skDragon v0.16 skript-yaml v1.3.2 SkQuery v3.6.5 
[21:48:26] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:48:26] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:48:26] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:48:26] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:48:26] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:48:26] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Stack trace:
[21:48:26] [Server thread/ERROR]: #!#! FieldAccessException: Field index out of bounds. (Index: 4, Size: 4)
[21:48:26] [Server thread/ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:367)
[21:48:26] [Server thread/ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343)
[21:48:26] [Server thread/ERROR]: #!#!     at com.morkaz.morkazsk.optionals.protocollib.EffShowParticleToPlayer.execute(EffShowParticleToPlayer.java:89)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:277)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:210)
[21:48:26] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[21:48:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[21:48:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
[21:48:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256)
[21:48:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[21:48:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173)
[21:48:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
[21:48:26] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Version Information:
[21:48:26] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha3 (latest)
[21:48:26] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:48:26] [Server thread/ERROR]: #!#!     Date: 2020-03-28
[21:48:26] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[21:48:26] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[21:48:26] [Server thread/ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[21:48:26] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.0-12-amd64
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Server platform: Paper
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Current node: null
[21:48:26] [Server thread/ERROR]: #!#! Current item: spawn [[long:20]] of particles "FLAME" for the player at (the player >> ch.njol.skript.classes.data.DefaultConverters$11@1caf1e68: entity -> location) offset by [[double:0.2]], [[double:0.2]], [[double:0.2]] with speed [[double:0.05]]
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Thread: Server thread
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! Language: english
[21:48:26] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:48:26] [Server thread/ERROR]: #!#! 
[21:48:26] [Server thread/ERROR]: #!#! End of Error.
[21:48:26] [Server thread/ERROR]: #!#! `

on loadup:
`[21:18:03] [Server thread/INFO]: [MorkazSk] Enabling MorkazSk v1.2
[21:18:03] [Server thread/WARN]: [MorkazSk] Loaded class ch.njol.skript.Skript from Skript v2.5-alpha3 which is not a depend, softdepend or loadbefore of this plugin.
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [35;22mProtocolLib [33;22madditional elements scheduled to load![0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [37;22m---------------------------------------------------[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [33;22mAmounts of registered elements:[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22m9 [33;22mEvents and [32;22m25 [33;22mEvent Values[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22m2 [33;22mConditions[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22m12 [33;22mEffects[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22m23 [33;22mExpressions[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22m0 [33;22mTypes[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [37;22m---------------------------------------------------[0m
[21:18:03] [Server thread/INFO]: [36;22m[MorkazSk] [32;22mPlugin enabled![0m```

**Comment by DampfWaffel** [comment]
on loadup:
https://pastebin.com/d4pvsEZC

on effect:
https://pastebin.com/VzxJBsgi

**Comment by MorkaZ** [comment]
It looks like protocollib changed their packet arguments. I will try to remove Protocollib dependency and use bukkit api to avoid problems like this one in future.
