### ISSUE TITLE
Unable to sort times

### ISSUE THREAD

**Issue by tandpfun** [MorkaZ/MorkazSk#26]
**Describe the problem**
I get this errror:
```
18.01 03:06:48 [Server] ERROR #!#! 
18.01 03:06:48 [Server] ERROR #!#! [Skript] Severe Error:
18.01 03:06:48 [Server] ERROR #!#! 
18.01 03:06:48 [Server] ERROR #!#! Something went horribly wrong with Skript.
18.01 03:06:48 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
18.01 03:06:48 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
18.01 03:06:48 [Server] ERROR #!#! Here is full list of them:
18.01 03:06:48 [Server] ERROR #!#! skRayFall v1.9.23 (https://sk.rayfall.net/) skript-reflect v2.1.0 (https://github.com/TPGamesNL/skript-reflect) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) skDragon v0.17 SkBee v1.9.1 (https://github.com/ShaneBeee/SkBee) Skungee v2.0.0-ALPHA-9 SkQuery v4.1.0 Reqn v1.2.1 
18.01 03:06:48 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
18.01 03:06:48 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
18.01 03:06:48 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
18.01 03:06:48 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
18.01 03:06:48 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
18.01 03:06:48 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
18.01 03:06:48 [Server] ERROR #!#! 
18.01 03:06:48 [Server] ERROR #!#! Stack trace:
18.01 03:06:48 [Server] ERROR #!#! java.lang.NumberFormatException: For input string: "12.899 seconds"
18.01 03:06:48 [Server] ERROR #!#!     at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
18.01 03:06:48 [Server] ERROR #!#!     at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
18.01 03:06:48 [Server] ERROR #!#!     at java.lang.Double.parseDouble(Double.java:538)
18.01 03:06:48 [Server] ERROR #!#!     at java.lang.Double.valueOf(Double.java:502)
18.01 03:06:48 [Server] ERROR #!#!     at com.morkaz.morkazsk.expressions.universal.ExprSortWithCustomOutput.lambda$get$0(ExprSortWithCustomOutput.java:94)
18.01 03:06:48 [Server] ERROR #!#!     at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
18.01 03:06:48 [Server] ERROR #!#!     at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
18.01 03:06:48 [Server] ERROR #!#!     at java.util.TimSort.sort(TimSort.java:220)
18.01 03:06:48 [Server] ERROR #!#!     at java.util.Arrays.sort(Arrays.java:1512)
18.01 03:06:48 [Server] ERROR #!#!     at java.util.ArrayList.sort(ArrayList.java:1464)
18.01 03:06:48 [Server] ERROR #!#!     at com.morkaz.morkazsk.expressions.universal.ExprSortWithCustomOutput.get(ExprSortWithCustomOutput.java:94)
```
When trying to sort times like this:
`set {_slevels::*} to sorted {db_.sbridging.best::*} from highest to lowest with format "@index"`

**Comment by SadShikawa** [comment]
Happens to me as well, it worked before i restarted the server. Have you found the issue?

**Comment by MorkaZ** [comment]
Sort is only created for numbers, not other types.
