### ISSUE TITLE
Problem with the update

### ISSUE THREAD

**Issue by Ishtar997** [MorkaZ/MorkazSk#36]
Hello
I have problems with the latest add-on
The problem occurs on the latest version of the script
This server is running Paper version git-Paper-305 (MC: 1.18.2) 
Skript Version: 2.6.1

```[17:10:44 WARN]: [MorkazSk] Loaded class ch.njol.skript.Skript from Skript v2.6.1 which is not a depend or softdepend of this plugin.
[17:10:44 ERROR]: #!#!
[17:10:44 ERROR]: #!#! [Skript] Severe Error:
[17:10:44 ERROR]: #!#! MorkazSk's class com.morkaz.morkazsk.events.EvtBlockFertilizeEvent generated an exception while loading
[17:10:44 ERROR]: #!#!
[17:10:44 ERROR]: #!#! Your server platform appears to be unsupported by Skript. It might not work reliably.
[17:10:44 ERROR]: #!#! You can report this at https://github.com/SkriptLang/Skript/issues. However, we may be unable to fix the issue.
[17:10:44 ERROR]: #!#! It is recommended that you switch to Paper or Spigot, should you encounter more problems.
[17:10:44 ERROR]: #!#!
[17:10:44 ERROR]: #!#! Stack trace:
[17:10:44 ERROR]: #!#! java.lang.IllegalStateException
[17:10:44 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript.getVersion(Skript.java:228)
[17:10:44 ERROR]: #!#!     at MorkazSk.jar//com.morkaz.morkazsk.events.EvtBlockFertilizeEvent.<clinit>(EvtBlockFertilizeEvent.java:15)
[17:10:44 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[17:10:44 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:488)
[17:10:44 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[17:10:44 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[17:10:44 ERROR]: #!#!     at MorkazSk.jar//com.morkaz.morkazsk.managers.RegisterManager.loadElementsClasses(RegisterManager.java:30)
[17:10:44 ERROR]: #!#!     at MorkazSk.jar//com.morkaz.morkazsk.MorkazSk.onEnable(MorkazSk.java:40)
[17:10:44 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:10:44 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:10:44 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[17:10:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[17:10:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[17:10:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[17:10:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[17:10:44 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[17:10:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[17:10:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:10:44 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[17:10:44 ERROR]: #!#!
[17:10:44 ERROR]: #!#! Version Information:
[17:10:44 ERROR]: Error occurred while enabling MorkazSk v1.3 (Is it up to date?)```

**Comment by MorkaZ** [comment]
Please, paste this error on pastebin.com or by using 3x "```" on both sides

**Comment by MorkaZ** [comment]
Does whole plugin not load because of this, or there are messages around pointing that MorkazSk will ignore this element and will load all rest features?
It looks like Skript bug because cause of this error is `Skript.jar//ch.njol.skript.Skript.getVersion(Skript.java:228)`

**Comment by MorkaZ** [comment]
I have created small workaround which will try to load everything without Skript's getVersion() if any exception will be catched.  Check last version.

**Comment by Ishtar997** [comment]
It’s all right now.
Thank you

I have also seen that you have other interesting plugins.
When can expect them to be updated?

**Comment by MorkaZ** [comment]
Maybe in next weeks. I am too busy right now.
