### ISSUE TITLE
Error occurred while enabling MorkazSk v1.2 (in skirpt 2.6.2)

### ISSUE THREAD

**Issue by gagore** [MorkaZ/MorkazSk#37]
> The previous version of 2.6.1(skript) worked without any problems, but the error occurred when I changed to 2.6.2(skript) version

```
 [17:05:47] [Server thread/ERROR]: Error occurred while enabling MorkazSk v1.2 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1222) ~[?:?]
	at ch.njol.skript.Skript.registerAddon(Skript.java:1244) ~[?:?]
	at com.morkaz.morkazsk.MorkazSk.onEnable(MorkazSk.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by MorkaZ** [comment]
Fixed in latest update

**Comment by gagore** [comment]
Thank you for your dedication
