### ISSUE TITLE
Reflection error on `set absorption hearts of player to 10`

### ISSUE THREAD

**Issue by Epikest** [MorkaZ/MorkazSk#41]
```
on load:
	set {bypass::*} to cookie and golden carrot
	set {cooldown::*} to golden apple, enchanted golden apple, cookie, honey bottle, glistering melon slice, and sugar

on right click:
	if {bypass::*} contains event-item:
		if player's hunger is 10:
			set player's hunger to 9.5
			set {_slot} to player's selected hotbar slot
			set {_event-item} to event-item
			while true is true:
				wait 1 tick
				stop loop if player's selected hotbar slot isn't {_slot}
				stop loop if event-item isn't {_event-item}
			add 0.5 to player's hunger
	if {cooldown::*} contains event-item:
		if cooldown of event-item for player is less than 1 tick:
			if event-item is sugar:
				wait 1 tick
				add 0.5 to player's health
				apply swiftness 2 to the player for 10 seconds 
				apply hunger 2 to the player for 10 seconds 
				remove 1 from item size of player's tool
				set cooldown of event-item for player to 5 seconds

on consume:
	if {bypass::*} contains event-item:
		if event-item isn't honey bottle:
			set absorption hearts of player to 10
	if {cooldown::*} contains event-item:
		if cooldown of event-item for player is less than 1 tick:
			if event-item is cookie:
				apply swiftness 2 to the player for 10 seconds
				apply hunger 1 to the player for 5 seconds
				set cooldown of event-item for player to 2.5 seconds
			if event-item is honey bottle:
				add 3 to player's health
			if event-item isn't cookie:
				set cooldown of event-item for player to 2.5 seconds
	if event-item is pumpkin pie:
		add 2 to player's health
```
eat a golden carrot and you get
```
[06:33:53 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.getAbsorptionHearts()
[06:33:53 WARN]:        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:659)
[06:33:53 WARN]:        at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1457)
[06:33:53 WARN]:        at java.base/java.lang.Class.getMethodHelper(Class.java:1543)
[06:33:53 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:1449)
[06:33:53 WARN]:        at MorkazSk.jar//com.morkaz.morkazsk.expressions.universal.ExprAbsorptionHeartsOfPlayer.getAbsorptionHearts(ExprAbsorptionHeartsOfPlayer.java:105)
[06:33:53 WARN]:        at MorkazSk.jar//com.morkaz.morkazsk.expressions.universal.ExprAbsorptionHeartsOfPlayer.change(ExprAbsorptionHeartsOfPlayer.java:82)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[06:33:53 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[06:33:53 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[06:33:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.v(EntityLiving.java:3952)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.v(EntityPlayer.java:1767)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:3814)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:2397)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.A(EntityLiving.java:3795)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2962)
[06:33:53 WARN]:        at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:300)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:686)
[06:33:53 WARN]:        at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:329)
[06:33:53 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:576)
[06:33:53 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:231)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1651)
[06:33:53 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[06:33:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
[06:33:53 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.setAbsorptionHearts(float)
[06:33:53 WARN]:        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:659)
[06:33:53 WARN]:        at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1457)
[06:33:53 WARN]:        at java.base/java.lang.Class.getMethodHelper(Class.java:1543)
[06:33:53 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:1449)
[06:33:53 WARN]:        at MorkazSk.jar//com.morkaz.morkazsk.expressions.universal.ExprAbsorptionHeartsOfPlayer.setAbsorptionHearts(ExprAbsorptionHeartsOfPlayer.java:116)
[06:33:53 WARN]:        at MorkazSk.jar//com.morkaz.morkazsk.expressions.universal.ExprAbsorptionHeartsOfPlayer.change(ExprAbsorptionHeartsOfPlayer.java:84)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[06:33:53 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[06:33:53 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[06:33:53 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[06:33:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.v(EntityLiving.java:3952)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.v(EntityPlayer.java:1767)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:3814)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:2397)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.A(EntityLiving.java:3795)
[06:33:53 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2962)
[06:33:53 WARN]:        at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:300)
[06:33:53 WARN]:        at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:686)
[06:33:53 WARN]:        at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:329)
[06:33:53 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:576)
[06:33:53 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:231)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1651)
[06:33:53 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[06:33:53 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[06:33:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:889)
```
plugins:
```
BKCommonLib (1.18.2-v2), Chunky (1.2.202), ClientStats (2.11.2), DiscordSRV (1.26.0-SNAPSHOT), DualWield (2.9), EffectKeeper (0.1), Essentials (2.19.5-dev+20-8d856dd), EssentialsChat (2.19.5-dev+20-8d856dd), FastPaths (0.1), floodgate (2.2.0-SNAPSHOT (b70-6e2c19f)), Geyser-Spigot (2.0.4-SNAPSHOT), Graves (4.8), GriefPrevention (16.18), HeadDrops (1.5.6), InstantNetherPortals (1.9), JukeLooper (2.2), LuckPerms (5.4.26), MorkazSk (1.3), NetherWater (1.0.2), OldschoolKill (2), PlaceholderAPI (2.11.1), PlugManX (2.3.0), ProjectileKnockback (1.9), ProtocolLib (4.8.0), ShulkerPacks (1.6.4), SkBee (1.16.1), Skellett (2.0.5), SkJade (1.4.1), Skript (2.6.2), skript-reflect (2.3), spark (1.9.11), StackableItems (1.1.0), Sudo (1.0.2), SwingThroughGrass (1.1-SNAPSHOT), TeaksTweaks (1.7.0-beta), Trails (0.9), TwerkFarm (1.1), VanillaTweaks (0.2.0-SNAPSHOT), Vault (1.7.3-b131), ViaBackwards (4.3.0), ViaVersion (4.3.1), WolvSK (1.7.2)
```

**Comment by MorkaZ** [comment]
send full errorlog, including top message

**Comment by MorkaZ** [comment]
Hello, please send full exception message, including top part.

**Comment by MorkaZ** [comment]
What minecraft version and server type are you using? It is strange EntityPlayer does not have this method in your server jar.

**Comment by Epikest** [comment]
> What minecraft version and server type are you using? It is strange EntityPlayer does not have this method in your server jar.

1.18.2 latest purpur
