### ISSUE TITLE
Error when clicking to armor stand

### ISSUE THREAD

**Issue by juzijun233** [MorkaZ/MorkazSk#42]
**Describe the problem**
```
 #!#!
[09:04:12 ERROR]: #!#! [Skript] Severe Error:
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Something went horribly wrong with Skript.
[09:04:12 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:04:12 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:04:12 ERROR]: #!#! Here is full list of them:
[09:04:12 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.27 (https://sk.rayfall.net/) SkriptJSON v1.0.0 SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) Skungee v2.0.0-BETA-2 skript-yaml v1.4 skScraft v1.5 Reqn v1.2.5 skript-db v1.3.6 RediSkript v1.3.6-SNAPSHOT skript-storage v1.2.2 identify which of those are specially related, so this might also be Skript issue.
[09:04:12 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:04:12 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:04:12 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:04:12 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:04:12 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:04:12 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Stack trace:
[09:04:12 ERROR]: #!#! java.lang.ClassCastException: class org.bukkit.event.player.PlayerInteractEntityEvent cannot be cast to class org.bukkit.event.player.PlayerArmorStandManipulateEvent (org.bukkit.event.player.PlayerInteractEntityEvent and org.bukkit.event.player.PlayerArmorStandManipulateEvent are in unnamed module of loader java.net.URLClassLoader @ee7d9f1)k 1.3beta.jar//com.morkaz.morkazsk.events.EvtArmorStandInteract$1.get(EvtArmorStandInteract.java:26)
[09:04:12 ERROR]: #!#!     at !Skript-Addon-MorkazSk 1.3beta.jar//com.morkaz.morkazsk.events.EvtArmorStandInteract$1.get(EvtArmorStandInteract.java:26)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.registrations.EventValues$3.get(EventValues.java:325)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.registrations.EventValues$3.get(EventValues.java:319)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:99)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:85)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:90)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:73)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:74)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:80)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[09:04:12 ERROR]: #!#!     at Skript[2.6.1].jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[09:04:12 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[09:04:12 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:04:12 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$6.performInteraction(PlayerConnection.java:2559)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2611)
[09:04:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[09:04:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2551)
[09:04:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[09:04:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[09:04:12 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:04:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:04:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1426)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[09:04:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1403)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1396)
[09:04:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1374)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1256)
[09:04:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[09:04:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Version Information:
[09:04:12 ERROR]: #!#!   Skript: 2.6.1
[09:04:12 ERROR]: #!#!     Flavor: skriptlang-github
[09:04:12 ERROR]: #!#!     Date: 22:18:42.554713200
[09:04:12 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[09:04:12 ERROR]: #!#!   Minecraft: 1.18.2
[09:04:12 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS)
[09:04:12 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Server platform: Paper
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Current node: null
[09:04:12 ERROR]: #!#! Current item: if the block is set
[09:04:12 ERROR]: #!#! Current trigger: rightclick (rightclick) (!OneBlood.sk, line 362)
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Thread: Server thread
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! Language: english
[09:04:12 ERROR]: #!#! Link parse mode: DISABLED
[09:04:12 ERROR]: #!#!
[09:04:12 ERROR]: #!#! End of Error.
```

**Comment by MorkaZ** [comment]
Hello, are you sure you are using latest MorkazSk?

**Comment by juzijun233** [comment]
> Hello, are you sure you are using latest MorkazSk?

no ,At that time it was still in this version

https://github.com/MorkaZ/MorkazSk/releases/tag/1.3-beta1

I will try the latest version later
