### ISSUE TITLE
can't load morkazSK

### ISSUE THREAD

**Issue by juzijun233** [MorkaZ/MorkazSk#43]
**Describe the problem**
: [MorkazSk] Enabling MorkazSk v1.3
[16:15:41 WARN]: [MorkazSk] Loaded class ch.njol.skript.Skript from Skript v2.6.2 which is not a depend, softdepend or loadbefore of this plugin.
[16:15:41 ERROR]: Error occurred while enabling MorkazSk v1.3 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
        at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1222) ~[!S[脚本]-Skript[2.6.2].jar:?]
        at ch.njol.skript.Skript.registerAddon(Skript.java:1244) ~[!S[脚本]-Skript[2.6.2].jar:?]
        at com.morkaz.morkazsk.MorkazSk.onEnable(MorkazSk.java:37) ~[!Skript-Addon-MorkazSk 1.3beta.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:15:41 INFO]: [MorkazSk] Disabling MorkazSk v1.3
[16:15:41 INFO]: [MorkazSk] Plugin disabled!
[16:15:41 INFO]: [Skript] Enabling Skript v2.6.2

**Comment by MorkaZ** [comment]
`[16:15:41 ERROR]: Error occurred while enabling MorkazSk v1.3 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization`   
Here you have answer. Skript itself denied this loading because you tried to enable it not when server was loading but after (or your modified server tried to do that).
