### ISSUE TITLE
The plugin is not loading

### ISSUE THREAD

**Issue by EnderdragonEggHatcher42069** [MorkaZ/MorkazSk#55]
**Describe the problem**
Error log:
[17:35:51 INFO]: [MorkazSk] Enabling MorkazSk v1.4
[17:35:51 ERROR]: Error occurred while enabling MorkazSk v1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
        at com.morkaz.morkazsk.managers.RegisterManager.loadElementsClasses(RegisterManager.java:29) ~[?:?]
        at com.morkaz.morkazsk.MorkazSk.onEnable(MorkazSk.java:40) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-PaperSpigot-e91f421c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[server.jar:git-PaperSpigot-e91f421c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) ~[server.jar:git-PaperSpigot-e91f421c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) ~[server.jar:git-PaperSpigot-e91f421c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:402) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:366) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:356) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:257) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:566) ~[server.jar:git-PaperSpigot-e91f421c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$0(MinecraftServer.java:133) ~[server.jar:git-PaperSpigot-e91f421c]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[server.jar:git-PaperSpigot-e91f421c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperSpigot-e91f421c]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 17 more
[17:35:51 INFO]: [MorkazSk] Disabling MorkazSk v1.4
[17:35:51 INFO]: [MorkazSk] Plugin disabled!

Server info:
https://dump.viaversion.com/0f7fa03dd2f4b58fbb729940b796b40d1c21d168ea9cf4e03f8a2344c56973e8

**Comment by NagasonicDev** [comment]
The addon most likely doesn't support version 1.8.8

**Comment by MorkaZ** [comment]
This addon doesnt support 1.8 minecraft servers. It has too many effects which work only with never versions and 1.8 API is lacking a lot of things.
